// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUMnTlIIXmUuFR3bBpM6bgE5vRP8mFNr0',
    appId: '1:925357046573:web:a7bae94443e095b0c531a4',
    messagingSenderId: '925357046573',
    projectId: 'firstappfirebase-efd59',
    authDomain: 'firstappfirebase-efd59.firebaseapp.com',
    storageBucket: 'firstappfirebase-efd59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjB2rqmezXcBE2XfRR9P_XZ19yCIBPnzw',
    appId: '1:925357046573:android:71cffe2a4dca0cdcc531a4',
    messagingSenderId: '925357046573',
    projectId: 'firstappfirebase-efd59',
    storageBucket: 'firstappfirebase-efd59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhaIdj_kZj_2sy9Jrfp4DnQpSeSqrQ7SA',
    appId: '1:925357046573:ios:047a1d97b98b678dc531a4',
    messagingSenderId: '925357046573',
    projectId: 'firstappfirebase-efd59',
    storageBucket: 'firstappfirebase-efd59.firebasestorage.app',
    iosBundleId: 'com.luis.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhaIdj_kZj_2sy9Jrfp4DnQpSeSqrQ7SA',
    appId: '1:925357046573:ios:047a1d97b98b678dc531a4',
    messagingSenderId: '925357046573',
    projectId: 'firstappfirebase-efd59',
    storageBucket: 'firstappfirebase-efd59.firebasestorage.app',
    iosBundleId: 'com.luis.appfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUMnTlIIXmUuFR3bBpM6bgE5vRP8mFNr0',
    appId: '1:925357046573:web:c585dff3caeddba8c531a4',
    messagingSenderId: '925357046573',
    projectId: 'firstappfirebase-efd59',
    authDomain: 'firstappfirebase-efd59.firebaseapp.com',
    storageBucket: 'firstappfirebase-efd59.firebasestorage.app',
  );
}
